### ISSUE TITLE
Visualization of heatmap

### ISSUE THREAD

**Issue by DingWB** [Isy89/LBF#2]
Hi @Isy89 ,

I came across this repository and I am glad that you used PyComplexHeatmap to plot the heatmap in your paper. 
Please kindly cite PyComplexHeatmap in your paper if you used it for publication.

**Comment by Isy89** [comment]
Hi @DingWB,

Thank you for bringing this to my attention. When I initially integrated **PyComplexHeatmap** into my code, there was no citation information available, and I unfortunately missed checking for updates later on.

I will look into whether it’s possible to add a citation to the LBFextract article, though since it was published in August, it might be challenging to make changes at this stage. However, I will definitely include a citation in the README of LBFextract and ensure it’s properly referenced in any future publications.

Thank you for your excellent work on **PyComplexHeatmap**!
